### PR TITLE
fix: remove default controls from Directions sample

### LINKED ISSUE #727: Default UI makes Directions sample cluttered
https://developers.google.com/maps/documentation/javascript/examples/directions-panel

I noticed that the custom control was overlapping the map type control. Since default controls aren't useful for this example, recommend disabling default controls. This is a one-line fix, just add the following property `disableDefaultUi: true`.

### PR DESCRIPTION
**Pull request by willum070**
The Directions Panel sample does not require any default map controls, and looks much better without them. This fix adds the  `disableDefaultUi: true` property, for a visually cleaner sample.

Fixes #727 🦕

### CODE REVIEW

File: samples/directions-panel/src/index.ts [hunk 1]
```diff
@@ -23,6 +23,7 @@ function initMap(): void {
     {
       zoom: 7,
       center: { lat: 41.85, lng: -87.65 },
+      disableDefaultUi: true,
```
Comment (jpoehnelt) [inline samples/directions-panel/src/index.ts:26]:
```suggestion
      disableDefaultUI: true,
```

**Review by jpoehnelt — APPROVED** [review]

**Review by willum070 — COMMENTED** [review]
Thanks!
